version: '3.8'

volumes:
 portainer: {}
services:
  mongodb:
    image: mongo:latest
    container_name: mongo_meli
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./.data:/data/db
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
      - 9000:9000
    volumes:
        - portainer:/data
        - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped